services:
  app:
    container_name: my_app
    tty: true
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"  # 追加: Prisma Studio用のポートフォワーディング
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgres://$DB_USER:$DB_PASS@db:5432/$DB_NAME
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: my_db
    image: postgres:16.3-alpine3.20
    hostname: db
    env_file:
      - ./.env
    networks:
      - app_network
    environment:
      - TZ=$DB_TZ
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  node_modules: